# -*- coding: utf-8 -*-
"""PANDA_RAG.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JrdglyuCOgBet5orWPZKJb78W-XBJdIL
"""

from google.colab import drive
drive.mount('/content/drive/')

!pip install langchain
!pip install openai
!pip install tiktoken
!pip install faiss-gpu
!pip install langchain_experimental
!pip install "langchain[docarray]"

!pip install python-docx

from langchain.chains import RetrievalQA
from langchain.chat_models import ChatOpenAI
from langchain.document_loaders import TextLoader
from langchain.vectorstores import DocArrayInMemorySearch
from IPython.display import display, Markdown
from langchain.text_splitter import CharacterTextSplitter
from langchain.embeddings import OpenAIEmbeddings, HuggingFaceInstructEmbeddings
from langchain.vectorstores import FAISS
from langchain.memory import ConversationBufferMemory
from langchain.chains import ConversationalRetrievalChain
from langchain.indexes import VectorstoreIndexCreator
from langchain_experimental.agents.agent_toolkits.csv.base import create_csv_agent
from langchain.agents.agent_types import AgentType
from langchain.memory import ConversationBufferMemory
import tiktoken

"""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


"""

import os
from docx import Document
from langchain.text_splitter import CharacterTextSplitter

# Prompt the user for their OpenAI API key
api_key = input("Please enter your OpenAI API key: ")

# Set the API key as an environment variable
os.environ["OPENAI_API_KEY"] = api_key

# Optionally, check that the environment variable was set correctly
print("OPENAI_API_KEY has been set!")

llm_model = "gpt-3.5-turbo"

# Path to the DOCX file
docx_file_path = '/content/drive/MyDrive/Data.txt/Custom Dataset.docx'

# Read the contents of the DOCX file
document = Document(docx_file_path)
doc_text = "\n".join([paragraph.text for paragraph in document.paragraphs])

# Split the text into chunks
text_splitter = CharacterTextSplitter(chunk_size=1500, chunk_overlap=200)
data = text_splitter.split_text(doc_text)

total_chunks = len(data)
print(f'Total number of chunks: {total_chunks}')

!pip install --upgrade tiktoken
!pip install --upgrade openai

data

!pip install numpy
!pip install faiss-cpu

class DocumentWrapper:
    def __init__(self, page_content, metadata=None):
        self.page_content = page_content
        self.metadata = metadata if metadata is not None else {}

# Assuming 'data' is a list of documents
documents = [DocumentWrapper(page_content) for page_content in data]

# Now you can use the vectorization code
embeddings = OpenAIEmbeddings()
vectorstore = FAISS.from_documents(documents, embedding=embeddings)

# Create conversation chain
llm = ChatOpenAI(temperature=0.7, model_name="gpt-3.5-turbo")
memory = ConversationBufferMemory(
memory_key='chat_history', return_messages=True)
conversation_chain = ConversationalRetrievalChain.from_llm(
        llm=llm,
        chain_type="stuff",
        retriever=vectorstore.as_retriever(),
        memory=memory
        )

query = "Jane, a 34-year-old professional, presents with recurrent and distressing thoughts about contamination and cleanliness. She feels compelled to engage in extensive handwashing rituals and avoids public spaces to prevent potential exposure to germs. These obsessive thoughts and compulsive behaviors significantly interfere with her daily life, impacting her ability to work, maintain relationships, and engage in routine activities. Jane acknowledges that her fears are excessive and irrational, yet the anxiety associated with contamination compels her to perform rituals repeatedly throughout the day. These symptoms have persisted for the past two years, causing marked distress and impairment in her overall functioning. What is this disorder?"
result = conversation_chain({"question": query})
answer = result["answer"]
answer

query = "got no one to talk to have no one around i ve been procrastinating on something for so long and i have no idea when i ll ever become serious or steadfast i just feel like a total waste i ve isolated myself which is making me go crazy right now no friend at all i m literally alone now feel like shit. What is this according to you?"
result = conversation_chain({"question": query})
answer = result["answer"]
answer

query = " I loved someone a lot once and that relationship lasted for 5 years and it was hard to overcome but anyhow someone came into my life and i overcame, it was going good bt after sometime it got worse frequent quarrel happend and clashes too after taht we decided to break up, and now i fear to get into any kinda relationship and basically i dont want to. What is this according to you?"
result = conversation_chain({"question": query})
answer = result["answer"]
answer

