# -*- coding: utf-8 -*-
"""PANDA_Chat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WpwcFb5viwbOc_irIr5XYXFXkRvC90Lj
"""

!pip install tiktoken
!pip install cohere
!pip install openai

!pip install --upgrade tiktoken
!pip install --upgrade openai

import openai

openai.api_key = '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'

def analyze_user_response(user_input):
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo-0613",
        messages=[
            {
                "role": "user",
                "content": f"Classify the following user response within the class [depression, anxiety, schizophrenia, ocd, ptsd, normal, Bipolar Disorder, Panic Disorder and Agoraphobia, Social Anxiety, Emotional Disorder, Borderline Personality Disorder]:\n\n{user_input}",
            }
        ],
        temperature=0.7,
    )
    return response['choices'][0]['message']['content']

user_input = ""

while "bye" not in user_input.lower():
    user_input = input("You: ")

    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {
                "role": "user",
                "content": user_input,
            }
        ],
        temperature=0.7,
    )

    print(f"Chatbot: {response['choices'][0]['message']['content']}")

    user_response_classification = analyze_user_response(user_input)
    print(f"User response classification: {user_response_classification}")

print("Chatbot: Goodbye!")

